spring:
  application:
    name: product
  profiles:
    active: peer1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/,http://localhost:5002/eureka/
  instance:
    hostname: localhost
    # 请求URL指向Eureka服务治理中心