spring:
  application:
    name: product
  profiles:
    active: peer1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/,http://localhost:5002/eureka/
  instance:
    hostname: localhost
<<<<<<< HEAD
    # 请求URL指向Eureka服务治理中心

FUND: # 代表只对资金微服务执行这样的配置
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl
    # 连接超时时间，单位毫秒
    ConnectTimeout: 1000
    # 请求超时时间：单位毫秒
    ReadTimeout: 3000
    # 最大连接数
    MaxTotalHttpConnections: 500
    # 每个服务提供者的最大连接数
    MaxConnectionsPerHost: 100
    # 是否所有操作都重试
    OkToRetryONAllOperations: false
    # 重试其他实例最大重试次数，不包括首次所选的server
    MaxAutoRetriesNextServer: 2
    # 同一实例的最大重试次数，不包括首次调用
    MaxAutoRetries: 1
  eureka:
    enabled: false
    listOfServers: http://localhost:5001,http://localhost:5002

ribbon:
  eager-load:
    # 是否启动饥渴加载
    enabled: true
    # 即可加载的服务ID
    clients: user,product,fund
=======
    # 请求URL指向Eureka服务治理中心
>>>>>>> ce45c9b3713495949ba406e619e7db16886d0e69
