spring:
  application:
    name: product
  profiles:
    active: peer2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
  instance:
    hostname: 192.168.80.1
    # 请求URL指向Eureka服务治理中心