# 请求URL指向Eureka服务治理中心
eureka:
  client:
    service-url:
      defaultZone : http://localhost:5001/eureka,http://localhost:5002/eureka/
#  instance:
#    hostname: localhost
# spring应用名称（微服务名称）
spring:
  application:
    name: user
  profiles:
    # 当配置为peer1时，application-peer1.yml配置文件生效
    # 当配置为peer2时，application-peer2.yml配置文件生效
    active: peer1
