spring:
  application:
    name: fund
  profiles:
    active: peer1
eureka:
  client:
    service-url:
      # 请求URL指向Eureka服务治理中心
      defaultZone: http://localhost:5001/eureka/,http://localhost:5002/eureka/
  # instance.hostname给 注册服务实例设置名称
  instance:
    hostname: localhost
