<<<<<<< HEAD
# 微服务端口
server:
  port: 6002

# 定义微服务实例信息
eureka:
  instance:
    metadata-map:
      # 自定义元数据版本号（version）为v2
      version: v2
      #  0-代表正常发布，1-代表灰色发布
=======
# 微服务端口
server:
  port: 6002

# 定义微服务实例信息
eureka:
  instance:
    metadata-map:
      # 自定义元数据版本号（version）为v2
      version: v2
      #  0-代表正常发布，1-代表灰色发布
>>>>>>> ce45c9b3713495949ba406e619e7db16886d0e69
      gray-release: 1